// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.proto;

public interface BuyerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.proto.Buyer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buyerId = 1;</code>
   */
  int getBuyerId();
}
