// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.proto;

public interface OrderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.proto.OrderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderId = 1;</code>
   */
  int getOrderId();

  /**
   * <code>int32 productId = 2;</code>
   */
  int getProductId();

  /**
   * <code>int64 orderTime = 3;</code>
   */
  long getOrderTime();

  /**
   * <code>string remark = 4;</code>
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 4;</code>
   */
  com.google.protobuf.ByteString
      getRemarkBytes();
}
