// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.proto;

public interface ProductInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.proto.ProductInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 productId = 1;</code>
   */
  int getProductId();

  /**
   * <code>int32 productNum = 2;</code>
   */
  int getProductNum();
}
